### ISSUE TITLE
[react] startSession throws Type error on 0.5.0

### ISSUE THREAD

**Issue by michalkot** [elevenlabs/packages#172]
Hi team,

I'm getting this error after upgrading to 0.5.0:
```
TypeError: this.options.onConnect is not a function
    at new i (BaseConversation.ts:96:18)
    at new I (VoiceConversation.ts:89:5)
    at I.startSession (VoiceConversation.ts:58:18)
```

The error goes away when I pass a dummy `onConnect` callback to the options
```
  const conversation = useConversation({
    // (... my other options)
    onConnect: () => {},
  });
```

I understand onConnect is supposed to be optional 🤔

**Comment by PaulAsjes** [comment]
Definitely intended to be optional, should be fixed now in v0.5.1!
