### ISSUE TITLE
@elevenlabs/react-native@1.2.0 cannot run on React Native without an extensive browser-globals polyfill — neither webrtc nor websocket connectionType works out of the box

### ISSUE THREAD

**Issue by rchauhan9** [elevenlabs/packages#766]
<h2>Summary</h2>
<p>Starting a conversation with the published <code>@elevenlabs/react-native@1.2.0</code> on a real React Native app (Expo SDK 54, RN 0.81, Hermes, iOS) fails on both <code>connectionType</code> modes:</p>
<ul>
<li><strong><code>webrtc</code></strong> crashes inside <code>livekit-client.Room</code> constructor and later inside <code>livekit-client.Track.attach()</code> because the SDK re-exports web-SDK code paths that reach for browser-only globals (<code>document</code>, <code>HTMLAudioElement</code>, <code>Event</code>, <code>CloseEvent</code>, <code>navigator.mediaDevices.addEventListener</code>, etc.).</li>
<li><strong><code>websocket</code></strong> crashes inside <code>MediaDeviceInput.create</code> (<code>@elevenlabs/client/dist/utils/input.js:45</code>) at <code>new window.AudioContext(...)</code> because Web Audio API is not available in React Native. The package itself acknowledges this as a known gap (see <a href="https://github.com/elevenlabs/packages/blob/main/packages/react-native/src/nativeVolume.ts"><code>nativeVolume.ts</code></a> — <em>"WebSocket volume on React Native is a known gap"</em>) but the comment understates the impact: it's not just volume, it's the entire input/output pipeline.</li>
</ul>
<p>The end result is that the published SDK is unusable on a fresh React Native app without a substantial workaround. The <code>examples/react-native-expo</code> reference app appears to work, but it consumes <code>@elevenlabs/react-native</code> via <code>workspace:*</code> and rebuilds locally (<code>pnpm build</code>), and its <code>metro.config.js</code> enforces singleton resolution for several packages — both of which mask the issue for users who install from npm.</p>
<p>This is reported separately from #661 (which is the same <code>webrtc</code>-mode <code>DOMException</code> symptom on <code>1.0.3</code>); this issue documents the broader pattern across both connection types and the architectural cause, with a workaround.</p>
<h2>Environment</h2>

  |  
-- | --
@elevenlabs/react-native | 1.2.0
@elevenlabs/client (transitive) | 1.7.0
@elevenlabs/react (transitive) | 1.6.0
@livekit/react-native | 2.9.6
@livekit/react-native-webrtc | 137.0.2
@livekit/react-native-expo-plugin | 1.0.2
@config-plugins/react-native-webrtc | 13.0.0
livekit-client (transitive) | 2.16.0 (also reproduced with 2.18.9)
expo | 54.0.33
react-native | 0.81.5
react | 19.1.0
JS engine | Hermes
Package manager | Bun (workspace monorepo)
Platform | iOS 18 simulator and device

<h2>Reproduction</h2>
<p>The minimal repro is the published <code>examples/react-native-expo</code> app with <code>@elevenlabs/react-native</code> installed from <strong>npm</strong> instead of <code>workspace:*</code>:</p>
<pre><code class="language-diff">// examples/react-native-expo/package.json
- "@elevenlabs/react-native": "workspace:*",
+ "@elevenlabs/react-native": "1.2.0",
</code></pre>
<p>…then <code>pnpm install</code>, <code>expo prebuild --clean</code>, <code>expo run:ios</code>, press <em>Start Conversation</em>. With <code>connectionType: "webrtc"</code> the app crashes in <code>Room</code> constructor (or <code>Track.attach()</code>, depending on which browser global is reached for first); with <code>connectionType: "websocket"</code> it crashes at <code>new window.AudioContext()</code>.</p>
<p>The same reproducer holds outside the example app — any RN 0.81 / Expo SDK 54 project consuming <code>@elevenlabs/react-native@1.2.0</code> directly from npm exhibits the same chain of crashes.</p>
<h2>Root cause analysis</h2>
<p>Three pieces of source make the issue clear.</p>
<p><strong>(1) <code>@elevenlabs/react-native/dist/index.react-native.js</code></strong> registers a "session setup strategy" that <em>wraps</em> <code>webSessionSetup</code> rather than replacing it:</p>
<pre><code class="language-js">async function reactNativeSessionSetup(options) {
    await AudioSession.configureAudio({ ... });
    await AudioSession.startAudioSession();
    const result = attachNativeVolume(await webSessionSetup(options));
    //                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    //                                  this is the WEB strategy
    ...
}
setSetupStrategy(reactNativeSessionSetup);
</code></pre>
<p><code>webSessionSetup</code> is the entry point into the web SDK's IO setup. The strategy wraps the <em>result</em> (so <code>attachNativeVolume</code> can replace volume providers afterward), but the underlying web code paths run unconditionally during the <code>await</code>.</p>
<p><strong>(2) <code>@elevenlabs/client/dist/platform/VoiceSessionSetup.js</code>'s <code>setupInputOutput</code></strong> calls one of two paths depending on the connection class. The <code>WebSocketConnection</code> branch unconditionally calls <code>MediaDeviceInput.create(...)</code> and <code>MediaDeviceOutput.create(...)</code>:</p>
<pre><code class="language-js">if (connection instanceof WebRTCConnection) {
    return { input: connection.input, output: connection.output, ... };
} else if (connection instanceof WebSocketConnection) {
    const [input, output] = await Promise.all([
        MediaDeviceInput.create({ ... }),    // ← needs AudioContext, AudioWorkletNode
        MediaDeviceOutput.create({ ... }),   // ← needs AudioContext
    ]);
    ...
}
</code></pre>
<p><strong>(3) <code>@elevenlabs/client/dist/utils/input.js:45</code></strong> is the AudioContext line:</p>
<pre><code class="language-js">context = new window.AudioContext(supportsSampleRateConstraint ? { sampleRate } : {});
const analyser = context.createAnalyser();
...
await loadRawAudioProcessor(context.audioWorklet, ...);
...
const worklet = new AudioWorkletNode(context, "rawAudioProcessor");
</code></pre>
<p><code>window.AudioContext</code>, <code>audioContext.audioWorklet</code>, and <code>AudioWorkletNode</code> are Web Audio API and don't exist in React Native — there's no native polyfill from <code>@livekit/react-native-webrtc</code> or anywhere else, because RN audio capture goes through the native AVAudioSession, not Web Audio. So <code>connectionType: "websocket"</code> cannot work without massive (and unrealistic) polyfilling — <code>AudioWorkletNode</code> in particular has no meaningful RN equivalent.</p>
<p>For <code>connectionType: "webrtc"</code>, <code>setupInputOutput</code> returns early and avoids <code>MediaDeviceInput</code>, but downstream code in <code>livekit-client</code> (the <code>Room</code> constructor at <code>~26182</code> and <code>Track.attach()</code> at <code>~13155</code> in 2.16.0; line numbers differ in 2.18.x) reaches for <code>document.createElement('audio')</code>, <code>window.addEventListener</code>, <code>navigator.mediaDevices.addEventListener</code>, etc. The web SDK's room event handlers (e.g., <code>WebRTCConnection.js:308</code>'s <code>room.on(TrackSubscribed, ...)</code> calling <code>track.attach()</code>) propagate this to userland-visible failures.</p>
<h2>What users see</h2>
<p>Without any polyfill, on first import of <code>@elevenlabs/react-native</code>:</p>
<pre><code>ReferenceError: Property 'DOMException' doesn't exist
  at &lt;global&gt; (mobile/app/(drawer)/index.tsx:N)
</code></pre>
<p>After <code>DOMException</code> is shimmed and <code>connectionType: "webrtc"</code> is selected, pressing Start triggers a cascade including (in approximate order, depending on how far each shim gets you):</p>
<pre><code>TypeError: _c.addEventListener is not a function (it is undefined)
  at Room#constructor (livekit-client.../livekit-client.esm.mjs:~26182)

ReferenceError: Property 'document' doesn't exist
  at Track#attach (livekit-client.../livekit-client.esm.mjs:~13155)

ReferenceError: Property 'CloseEvent' doesn't exist
ReferenceError: Property 'Event' doesn't exist
ReferenceError: Property 'HTMLVideoElement' doesn't exist
ReferenceError: Property 'HTMLAudioElement' doesn't exist
TypeError: window.removeEventListener is not a function (it is undefined)
</code></pre>
<p>Each surfaces from a different <code>livekit-client</code> code path. They're not reachable from <code>connectionType: "websocket"</code> because that mode dies earlier in <code>MediaDeviceInput.create</code>:</p>
<pre><code>TypeError: Cannot read property 'prototype' of undefined
  at MediaDeviceInput.create (@elevenlabs/client/dist/utils/input.js:45)
  at setupInputOutput (@elevenlabs/client/dist/platform/VoiceSessionSetup.js:23)
  at webSessionSetup (@elevenlabs/client/dist/platform/VoiceSessionSetup.js:58)
  at reactNativeSessionSetup (@elevenlabs/react-native/dist/index.react-native.js:25)
</code></pre>
<p>(<code>Cannot read property 'prototype' of undefined</code> here is <code>new undefined(...)</code> — <code>window.AudioContext</code> is undefined.)</p>
<h2>Workaround</h2>
<p>Two changes get a real RN app working with the published <code>1.2.0</code>. Neither is appropriate as a long-term solution; documenting them here so other affected users can ship.</p>
<h3>1. Comprehensive browser-globals polyfill, loaded before <code>expo-router/entry</code></h3>
<p>Create a polyfill module that runs first via a custom entry point. The polyfill needs to install: <code>DOMException</code>, the <code>Event</code> family (<code>Event</code>, <code>MessageEvent</code>, <code>ErrorEvent</code>, <code>CloseEvent</code>), <code>window</code> (aliased to <code>globalThis</code> plus listener stubs), <code>document</code> with <code>createElement('audio'|'video')</code> returning real <code>HTMLAudioElement</code>/<code>HTMLVideoElement</code> class instances (so <code>instanceof</code> checks in <code>livekit-client</code> pass), <code>HTMLElement</code>/<code>HTMLMediaElement</code>/<code>HTMLAudioElement</code>/<code>HTMLVideoElement</code> classes, <code>navigator.mediaDevices.{addEventListener,removeEventListener,getSupportedConstraints}</code>, <code>location</code> with <code>href</code>, and an <code>AudioContext</code> stub with full analyser methods.</p>
<p>The shim is intentionally a no-op for actual functionality — real audio plays through <code>@livekit/react-native-webrtc</code>'s native pipeline regardless of what the JS-side <code>Track.attach()</code> does with its fake <code>&lt;audio&gt;</code> element. The polyfill exists only to keep livekit-client's web code paths from throwing during room initialization and track subscription. (Full source available on request; ~150 lines.)</p>
<p><code>mobile/index.js</code>:</p>
<pre><code class="language-js">import './lib/polyfills';      // must run before any module that imports @elevenlabs/* or @livekit/*
import 'expo-router/entry';
</code></pre>
<p><code>mobile/package.json</code>:</p>
<pre><code class="language-json">"main": "./index.js"
</code></pre>
<h3>2. Singleton resolution in <code>metro.config.js</code></h3>
<p>In any monorepo (pnpm or bun), Metro can resolve <code>@livekit/react-native</code> and <code>@livekit/react-native-webrtc</code> to multiple physical copies depending on the importer. <code>registerGlobals()</code> then runs against one copy while consumers see another, leading to incoherent behavior. Force singleton resolution exactly as the example's <code>metro.config.js</code> does:</p>
<pre><code class="language-js">const singletonPackages = {
  'react': path.resolve(appNodeModules, 'react'),
  'react-native': path.resolve(appNodeModules, 'react-native'),
  '@livekit/react-native': path.resolve(appNodeModules, '@livekit/react-native'),
  '@livekit/react-native-webrtc': path.resolve(appNodeModules, '@livekit/react-native-webrtc'),
};
</code></pre>
<p>Without this, even with the polyfill, the WebRTC native module ends up with multiple JS-side wrappers competing for one native module.</p>
<h3>Connection mode</h3>
<p>Only <code>connectionType: "webrtc"</code> is viable; <code>connectionType: "websocket"</code> is unreachable per <code>nativeVolume.ts</code>'s own comment.</p>
<h3>Version pinning</h3>
<p>Match the example app exactly: <code>livekit-client@2.16.0</code> (override at workspace root), <code>@livekit/react-native@2.9.6</code>, <code>@livekit/react-native-webrtc@137.0.2</code>, <code>@config-plugins/react-native-webrtc@13.0.0</code>. Other version combinations also break in different ways.</p>
<h2>Suggested fixes</h2>
<p>In rough order of effort/impact:</p>
<ol>
<li><strong>Document the constraints honestly.</strong> The README currently positions <code>@elevenlabs/react-native</code> as a working RN companion to <code>@elevenlabs/react</code>. In its current state it isn't — neither connection mode works on RN without the workaround above. A README note explaining the known gaps (or, more usefully, a "RN setup checklist" with the polyfills and metro config) would save users the long debugging path.</li>
<li><strong>Replace, don't wrap, the IO setup in the RN strategy.</strong> <code>setupInputOutput</code> is the bridge to web-only code; the RN strategy should provide its own implementation that uses native input/output (analogous to what <code>attachNativeVolume</code> does for volume providers). This would let <code>connectionType: "websocket"</code> actually work on RN and remove the <code>livekit-client</code> web-DOM dependency from the WebRTC path's room initialization.</li>
<li><strong>Ship the polyfills as part of <code>@elevenlabs/react-native</code></strong> itself, registered as a side effect of importing the package's RN entry. The current side effects only call <code>registerGlobals()</code> from <code>@livekit/react-native</code>, which doesn't cover <code>document</code>, <code>Event</code>, <code>HTMLMediaElement</code>, etc. — exactly the surface where the failures land.</li>
<li><strong>Verify the example reproduces from npm.</strong> Right now the example consumes <code>workspace:*</code> and a fresh user installing <code>@elevenlabs/react-native@1.2.0</code> from npm in the same configuration won't get the same behavior. An end-to-end test that actually runs the example against a published version would catch regressions like this.</li>
</ol>
<p>Happy to provide the full polyfill source, a minimal failing repro repo, additional logs, or a PR if any of (1)–(3) would be useful.</p></body></html># `@elevenlabs/react-native@1.2.0` cannot run on React Native without an extensive browser-globals polyfill — neither `webrtc` nor `websocket` `connectionType` works out of the box

## Summary

Starting a conversation with the published `@elevenlabs/react-native@1.2.0` on a real React Native app (Expo SDK 54, RN 0.81, Hermes, iOS) fails on both `connectionType` modes:

- **`webrtc`** crashes inside `livekit-client.Room` constructor and later inside `livekit-client.Track.attach()` because the SDK re-exports web-SDK code paths that reach for browser-only globals (`document`, `HTMLAudioElement`, `Event`, `CloseEvent`, `navigator.mediaDevices.addEventListener`, etc.).
- **`websocket`** crashes inside `MediaDeviceInput.create` (`@elevenlabs/client/dist/utils/input.js:45`) at `new window.AudioContext(...)` because Web Audio API is not available in React Native. The package itself acknowledges this as a known gap (see [`[nativeVolume.ts](https://github.com/elevenlabs/packages/blob/main/packages/react-native/src/nativeVolume.ts)`](https://github.com/elevenlabs/packages/blob/main/packages/react-native/src/nativeVolume.ts) — *"WebSocket volume on React Native is a known gap"*) but the comment understates the impact: it's not just volume, it's the entire input/output pipeline.

The end result is that the published SDK is unusable on a fresh React Native app without a substantial workaround. The `examples/react-native-expo` reference app appears to work, but it consumes `@elevenlabs/react-native` via `workspace:*` and rebuilds locally (`pnpm build`), and its `metro.config.js` enforces singleton resolution for several packages — both of which mask the issue for users who install from npm.

This is reported separately from #661 (which is the same `webrtc`-mode `DOMException` symptom on `1.0.3`); this issue documents the broader pattern across both connection types and the architectural cause, with a workaround.

## Environment

| | |
|---|---|
| `@elevenlabs/react-native` | `1.2.0` |
| `@elevenlabs/client` (transitive) | `1.7.0` |
| `@elevenlabs/react` (transitive) | `1.6.0` |
| `@livekit/react-native` | `2.9.6` |
| `@livekit/react-native-webrtc` | `137.0.2` |
| `@livekit/react-native-expo-plugin` | `1.0.2` |
| `@config-plugins/react-native-webrtc` | `13.0.0` |
| `livekit-client` (transitive) | `2.16.0` (also reproduced with `2.18.9`) |
| `expo` | `54.0.33` |
| `react-native` | `0.81.5` |
| `react` | `19.1.0` |
| JS engine | Hermes |
| Package manager | Bun (workspace monorepo) |
| Platform | iOS 18 simulator and device |

## Reproduction

The minimal repro is the published `examples/react-native-expo` app with `@elevenlabs/react-native` installed from **npm** instead of `workspace:*`:

```diff
// examples/react-native-expo/package.json
- "@elevenlabs/react-native": "workspace:*",
+ "@elevenlabs/react-native": "1.2.0",
```

…then `pnpm install`, `expo prebuild --clean`, `expo run:ios`, press *Start Conversation*. With `connectionType: "webrtc"` the app crashes in `Room` constructor (or `Track.attach()`, depending on which browser global is reached for first); with `connectionType: "websocket"` it crashes at `new window.AudioContext()`.

The same reproducer holds outside the example app — any RN 0.81 / Expo SDK 54 project consuming `@elevenlabs/react-native@1.2.0` directly from npm exhibits the same chain of crashes.

## Root cause analysis

Three pieces of source make the issue clear.

**(1) `@elevenlabs/react-native/dist/index.react-native.js`** registers a "session setup strategy" that *wraps* `webSessionSetup` rather than replacing it:

```js
async function reactNativeSessionSetup(options) {
    await AudioSession.configureAudio({ ... });
    await AudioSession.startAudioSession();
    const result = attachNativeVolume(await webSessionSetup(options));
    //                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    //                                  this is the WEB strategy
    ...
}
setSetupStrategy(reactNativeSessionSetup);
```

`webSessionSetup` is the entry point into the web SDK's IO setup. The strategy wraps the *result* (so `attachNativeVolume` can replace volume providers afterward), but the underlying web code paths run unconditionally during the `await`.

**(2) `@elevenlabs/client/dist/platform/VoiceSessionSetup.js`'s `setupInputOutput`** calls one of two paths depending on the connection class. The `WebSocketConnection` branch unconditionally calls `MediaDeviceInput.create(...)` and `MediaDeviceOutput.create(...)`:

```js
if (connection instanceof WebRTCConnection) {
    return { input: connection.input, output: connection.output, ... };
} else if (connection instanceof WebSocketConnection) {
    const [input, output] = await Promise.all([
        MediaDeviceInput.create({ ... }),    // ← needs AudioContext, AudioWorkletNode
        MediaDeviceOutput.create({ ... }),   // ← needs AudioContext
    ]);
    ...
}
```

**(3) `@elevenlabs/client/dist/utils/input.js:45`** is the AudioContext line:

```js
context = new window.AudioContext(supportsSampleRateConstraint ? { sampleRate } : {});
const analyser = context.createAnalyser();
...
await loadRawAudioProcessor(context.audioWorklet, ...);
...
const worklet = new AudioWorkletNode(context, "rawAudioProcessor");
```

`window.AudioContext`, `audioContext.audioWorklet`, and `AudioWorkletNode` are Web Audio API and don't exist in React Native — there's no native polyfill from `@livekit/react-native-webrtc` or anywhere else, because RN audio capture goes through the native AVAudioSession, not Web Audio. So `connectionType: "websocket"` cannot work without massive (and unrealistic) polyfilling — `AudioWorkletNode` in particular has no meaningful RN equivalent.

For `connectionType: "webrtc"`, `setupInputOutput` returns early and avoids `MediaDeviceInput`, but downstream code in `livekit-client` (the `Room` constructor at `~26182` and `Track.attach()` at `~13155` in 2.16.0; line numbers differ in 2.18.x) reaches for `document.createElement('audio')`, `window.addEventListener`, `navigator.mediaDevices.addEventListener`, etc. The web SDK's room event handlers (e.g., `WebRTCConnection.js:308`'s `room.on(TrackSubscribed, ...)` calling `track.attach()`) propagate this to userland-visible failures.

## What users see

Without any polyfill, on first import of `@elevenlabs/react-native`:

```
ReferenceError: Property 'DOMException' doesn't exist
  at <global> (mobile/app/(drawer)/index.tsx:N)
```

After `DOMException` is shimmed and `connectionType: "webrtc"` is selected, pressing Start triggers a cascade including (in approximate order, depending on how far each shim gets you):

```
TypeError: _c.addEventListener is not a function (it is undefined)
  at Room#constructor (livekit-client.../livekit-client.esm.mjs:~26182)

ReferenceError: Property 'document' doesn't exist
  at Track#attach (livekit-client.../livekit-client.esm.mjs:~13155)

ReferenceError: Property 'CloseEvent' doesn't exist
ReferenceError: Property 'Event' doesn't exist
ReferenceError: Property 'HTMLVideoElement' doesn't exist
ReferenceError: Property 'HTMLAudioElement' doesn't exist
TypeError: window.removeEventListener is not a function (it is undefined)
```

Each surfaces from a different `livekit-client` code path. They're not reachable from `connectionType: "websocket"` because that mode dies earlier in `MediaDeviceInput.create`:

```
TypeError: Cannot read property 'prototype' of undefined
  at MediaDeviceInput.create (@elevenlabs/client/dist/utils/input.js:45)
  at setupInputOutput (@elevenlabs/client/dist/platform/VoiceSessionSetup.js:23)
  at webSessionSetup (@elevenlabs/client/dist/platform/VoiceSessionSetup.js:58)
  at reactNativeSessionSetup (@elevenlabs/react-native/dist/index.react-native.js:25)
```

(`Cannot read property 'prototype' of undefined` here is `new undefined(...)` — `window.AudioContext` is undefined.)

## Workaround

Two changes get a real RN app working with the published `1.2.0`. Neither is appropriate as a long-term solution; documenting them here so other affected users can ship.

### 1. Comprehensive browser-globals polyfill, loaded before `expo-router/entry`

Create a polyfill module that runs first via a custom entry point. The polyfill needs to install: `DOMException`, the `Event` family (`Event`, `MessageEvent`, `ErrorEvent`, `CloseEvent`), `window` (aliased to `globalThis` plus listener stubs), `document` with `createElement('audio'|'video')` returning real `HTMLAudioElement`/`HTMLVideoElement` class instances (so `instanceof` checks in `livekit-client` pass), `HTMLElement`/`HTMLMediaElement`/`HTMLAudioElement`/`HTMLVideoElement` classes, `navigator.mediaDevices.{addEventListener,removeEventListener,getSupportedConstraints}`, `location` with `href`, and an `AudioContext` stub with full analyser methods.

The shim is intentionally a no-op for actual functionality — real audio plays through `@livekit/react-native-webrtc`'s native pipeline regardless of what the JS-side `Track.attach()` does with its fake `<audio>` element. The polyfill exists only to keep livekit-client's web code paths from throwing during room initialization and track subscription. (Full source available on request; ~150 lines.)

`mobile/index.js`:
```js
import './lib/polyfills';      // must run before any module that imports @elevenlabs/* or @livekit/*
import 'expo-router/entry';
```

`mobile/package.json`:
```json
"main": "./index.js"
```

### 2. Singleton resolution in `metro.config.js`

In any monorepo (pnpm or bun), Metro can resolve `@livekit/react-native` and `@livekit/react-native-webrtc` to multiple physical copies depending on the importer. `registerGlobals()` then runs against one copy while consumers see another, leading to incoherent behavior. Force singleton resolution exactly as the example's `metro.config.js` does:

```js
const singletonPackages = {
  'react': path.resolve(appNodeModules, 'react'),
  'react-native': path.resolve(appNodeModules, 'react-native'),
  '@livekit/react-native': path.resolve(appNodeModules, '@livekit/react-native'),
  '@livekit/react-native-webrtc': path.resolve(appNodeModules, '@livekit/react-native-webrtc'),
};
```

Without this, even with the polyfill, the WebRTC native module ends up with multiple JS-side wrappers competing for one native module.

### Connection mode

Only `connectionType: "webrtc"` is viable; `connectionType: "websocket"` is unreachable per `nativeVolume.ts`'s own comment.

### Version pinning

Match the example app exactly: `livekit-client@2.16.0` (override at workspace root), `@livekit/react-native@2.9.6`, `@livekit/react-native-webrtc@137.0.2`, `@config-plugins/react-native-webrtc@13.0.0`. Other version combinations also break in different ways.

## Suggested fixes

In rough order of effort/impact:

1. **Document the constraints honestly.** The README currently positions `@elevenlabs/react-native` as a working RN companion to `@elevenlabs/react`. In its current state it isn't — neither connection mode works on RN without the workaround above. A README note explaining the known gaps (or, more usefully, a "RN setup checklist" with the polyfills and metro config) would save users the long debugging path.
2. **Replace, don't wrap, the IO setup in the RN strategy.** `setupInputOutput` is the bridge to web-only code; the RN strategy should provide its own implementation that uses native input/output (analogous to what `attachNativeVolume` does for volume providers). This would let `connectionType: "websocket"` actually work on RN and remove the `livekit-client` web-DOM dependency from the WebRTC path's room initialization.
3. **Ship the polyfills as part of `@elevenlabs/react-native`** itself, registered as a side effect of importing the package's RN entry. The current side effects only call `registerGlobals()` from `@livekit/react-native`, which doesn't cover `document`, `Event`, `HTMLMediaElement`, etc. — exactly the surface where the failures land.
4. **Verify the example reproduces from npm.** Right now the example consumes `workspace:*` and a fresh user installing `@elevenlabs/react-native@1.2.0` from npm in the same configuration won't get the same behavior. An end-to-end test that actually runs the example against a published version would catch regressions like this.

Happy to provide the full polyfill source, a minimal failing repro repo, additional logs, or a PR if any of (1)–(3) would be useful.

**Comment by kraenhansen** [comment]
Thanks for this incredibly thorough report and root cause analysis. It looks like the description may have been duplicated, would you mind cleaning that up?

I can confirm the issue: the RN session setup wraps rather than replaces the web IO strategy, hitting browser-only code paths. We're working on removing the Client SDK's reliance on DOM APIs in #671, which should address the root cause. In the meantime, the workarounds you've documented are a great reference for other affected users.

**Comment by markoupshift** [comment]
Hey @rchauhan9  , I’m facing the same issue. You mentioned you have a ~150-line polyfill temporary solution available on request - could you share it here or link to a gist when you get a chance?

Thank you.

**Comment by rchauhan9** [comment]
> Hey [@rchauhan9](https://github.com/rchauhan9) , I’m facing the same issue. You mentioned you have a ~150-line polyfill temporary solution available on request - could you share it here or link to a gist when you get a chance?
> 
> Thank you.

Sure here was my polyfills.ts file
```typescript
import { registerGlobals } from '@livekit/react-native';

registerGlobals();

const g = globalThis as any;

// DOMException — Hermes on RN 0.81 doesn't expose it
if (typeof g.DOMException === 'undefined') {
  g.DOMException = class DOMException extends Error {
    code: number;
    constructor(message?: string, name = 'Error') {
      super(message);
      this.name = name;
      this.code = 0;
    }
  };
}

// Event listener stubs on globalThis
if (typeof g.addEventListener !== 'function') {
  g.addEventListener = () => {};
  g.removeEventListener = () => {};
  g.dispatchEvent = () => true;
}
if (typeof g.window === 'undefined') g.window = g;

// Event family
class FakeEvent {
  type: string; bubbles: boolean; cancelable: boolean;
  defaultPrevented = false; timeStamp: number;
  target: any = null; currentTarget: any = null;
  constructor(type: string, init: any = {}) {
    this.type = type;
    this.bubbles = !!init.bubbles;
    this.cancelable = !!init.cancelable;
    this.timeStamp = Date.now();
  }
  preventDefault() { this.defaultPrevented = true; }
  stopPropagation() {}
  stopImmediatePropagation() {}
}
if (typeof g.Event === 'undefined') g.Event = FakeEvent;
if (typeof g.MessageEvent === 'undefined') {
  g.MessageEvent = class extends FakeEvent {
    data: any; origin: string; lastEventId: string; source: any; ports: any[];
    constructor(type: string, init: any = {}) {
      super(type, init);
      this.data = init.data ?? null;
      this.origin = init.origin ?? '';
      this.lastEventId = init.lastEventId ?? '';
      this.source = init.source ?? null;
      this.ports = init.ports ?? [];
    }
  };
}
if (typeof g.ErrorEvent === 'undefined') {
  g.ErrorEvent = class extends FakeEvent {
    message: string; filename: string; lineno: number; colno: number; error: any;
    constructor(type: string, init: any = {}) {
      super(type, init);
      this.message = init.message ?? '';
      this.filename = init.filename ?? '';
      this.lineno = init.lineno ?? 0;
      this.colno = init.colno ?? 0;
      this.error = init.error ?? null;
    }
  };
}
if (typeof g.CloseEvent === 'undefined') {
  g.CloseEvent = class extends FakeEvent {
    code: number; reason: string; wasClean: boolean;
    constructor(type: string, init: any = {}) {
      super(type, init);
      this.code = init.code ?? 1000;
      this.reason = init.reason ?? '';
      this.wasClean = init.wasClean ?? false;
    }
  };
}

// HTML media elements (instanceof checks in livekit-client)
class HTMLElement {
  setAttribute() {}
  removeAttribute() {}
  remove() {}
  addEventListener() {}
  removeEventListener() {}
  dispatchEvent() { return true; }
  style: any = {};
  children: any[] = [];
  appendChild() {}
  removeChild() {}
}
class HTMLMediaElement extends HTMLElement {
  srcObject: any = null;
  muted = false;
  autoplay = false;
  paused = true;
  volume = 1;
  currentTime = 0;
  duration = 0;
  readyState = 0;
  _listeners = new Map<string, Set<Function>>();
  addEventListener(type: string, fn: Function) {
    if (!this._listeners.has(type)) this._listeners.set(type, new Set());
    this._listeners.get(type)!.add(fn);
  }
  removeEventListener(type: string, fn: Function) { this._listeners.get(type)?.delete(fn); }
  play() { this.paused = false; return Promise.resolve(); }
  pause() { this.paused = true; }
  load() {}
}
class HTMLAudioElement extends HTMLMediaElement {}
class HTMLVideoElement extends HTMLMediaElement {
  videoWidth = 0;
  videoHeight = 0;
}
if (typeof g.HTMLElement === 'undefined') g.HTMLElement = HTMLElement;
if (typeof g.HTMLMediaElement === 'undefined') g.HTMLMediaElement = HTMLMediaElement;
if (typeof g.HTMLAudioElement === 'undefined') g.HTMLAudioElement = HTMLAudioElement;
if (typeof g.HTMLVideoElement === 'undefined') g.HTMLVideoElement = HTMLVideoElement;

// document shim — Track.attach() needs createElement('audio')
if (typeof g.document === 'undefined') {
  g.document = {
    createElement: (tag: string) => {
      if (tag === 'audio') return new HTMLAudioElement();
      if (tag === 'video') return new HTMLVideoElement();
      return new HTMLElement();
    },
    createTextNode: () => ({}),
    addEventListener() {},
    removeEventListener() {},
    dispatchEvent: () => true,
    body: { appendChild() {}, removeChild() {} },
    head: { appendChild() {}, removeChild() {} },
    documentElement: { style: {} },
    visibilityState: 'visible',
    hidden: false,
    readyState: 'complete',
  };
}

// Navigator
if (typeof g.navigator === 'undefined') g.navigator = {};
if (typeof g.navigator.userAgent === 'undefined') g.navigator.userAgent = 'react-native';
if (typeof g.navigator.onLine === 'undefined') g.navigator.onLine = true;

if (typeof g.navigator.addEventListener !== 'function') {
  g.navigator.addEventListener = () => {};
  g.navigator.removeEventListener = () => {};
  g.navigator.dispatchEvent = () => true;
}

// AudioContext stub — used in WARN-level code paths even on WebRTC
if (typeof g.AudioContext === 'undefined') {
  g.AudioContext = class {
    state = 'running';
    sampleRate = 48000;
    destination = { connect() {}, disconnect() {} };
    createAnalyser() {
      return {
        fftSize: 2048,
        frequencyBinCount: 1024,
        smoothingTimeConstant: 0.8,
        minDecibels: -100,
        maxDecibels: -30,
        getByteTimeDomainData(arr: Uint8Array) { arr.fill(128); },
        getByteFrequencyData(arr: Uint8Array) { arr.fill(0); },
        getFloatTimeDomainData(arr: Float32Array) { arr.fill(0); },
        getFloatFrequencyData(arr: Float32Array) { arr.fill(-Infinity); },
        connect() {}, disconnect() {},
      };
    }
    createMediaStreamSource() { return { connect() {}, disconnect() {} }; }
    createGain() { return { gain: { value: 1 }, connect() {}, disconnect() {} }; }
    close() { return Promise.resolve(); }
    resume() { return Promise.resolve(); }
    suspend() { return Promise.resolve(); }
  };
}

// Lazy-patch navigator.mediaDevices.getSupportedConstraints
const installMediaDevicesShim = () => {
  const md = g.navigator?.mediaDevices;
  if (!md) {
    setTimeout(installMediaDevicesShim, 0);
    return;
  }
  if (typeof md.getSupportedConstraints !== 'function') {
    md.getSupportedConstraints = () => ({
      autoGainControl: true,
      channelCount: true,
      echoCancellation: true,
      noiseSuppression: true,
      sampleRate: true,
      sampleSize: true,
    });
  }
  if (typeof md.addEventListener !== 'function') {
    md.addEventListener = () => {};
    md.removeEventListener = () => {};
    md.dispatchEvent = () => true;
  }
};
installMediaDevicesShim();

// Location — axios and other libs read location.href when window is defined
if (typeof g.location === 'undefined') {
  g.location = {
    href: '',
    protocol: 'https:',
    host: '',
    hostname: '',
    port: '',
    pathname: '/',
    search: '',
    hash: '',
    origin: '',
    reload() {},
    assign() {},
    replace() {},
  };
}
```

and then in a index.js
```typescript
import './lib/polyfills';
import 'expo-router/entry';
```
